// list of constants

module.exports = {

	// Errors
	ERROR_INVALID: 'INVALID_VALUE',
	ERROR_UNIQUE: 'EXPECTED_UNIQUE_VALUE',
	ERROR_NOT_FOUND: 'NOT_FOUND',
	ERROR_REQUIRED: 'REQUIRED',
	ERROR_AUTH_REQUIRED: 'AUTH_REQUIRED',
	ERROR_ACCESS_DENIED: 'ACCESS_DENIED',
	ERROR_INTERNAL: 'INTERNAL_ERROR',
	ERROR_TYPE: 'WRONG_TYPE',
	ERROR_TIME_RESTRICTION: 'TIME_RESTRICTION',
	ERROR_VOTE_TWICE: 'VOTE_TWICE',
	ERROR_ALREADY_REMOVED: 'ALREADY_REMOVED',

	// things
	ROLES: {
		USER: 1,
		MODERATOR: 5,
		ADMIN: 10
	},
	
	// stages
	STAGES: [
		'FINAL',
		'SEMIFINAL',
		'QUARTERFINAL',
		'RO16',
		'RO32',
		'RO64',
		'GROUPA',
		'GROUPB',
		'GROUPC',
		'GROUPD'
	]
};
