// list of constants

module.exports = {
	
	// Errors
	ERROR_INVALID: 'INVALID_VALUE',
	ERROR_UNIQUE: 'EXPECTED_UNIQUE_VALUE',
	ERROR_NOT_FOUND: 'NOT_FOUND',
	ERROR_REQUIRED: 'REQUIRED',
	ERROR_ACCESS_DENIED: 'ACCESS_DENIED',
	ERROR_INTERNAL: 'INTERNAL_ERROR'
};
	