// list of constants

module.exports = {

	// Errors
	ERROR_INVALID: 'INVALID_VALUE',
	ERROR_UNIQUE: 'EXPECTED_UNIQUE_VALUE',
	ERROR_NOT_FOUND: 'NOT_FOUND',
	ERROR_REQUIRED: 'REQUIRED',
	ERROR_ACCESS_DENIED: 'ACCESS_DENIED',
	ERROR_INTERNAL: 'INTERNAL_ERROR',
	ERROR_TYPE: 'WRONG_TYPE',
	ERROR_TIME_RESTRICTION: 'TIME_RESTRICTION',
	ERROR_VOTE_TWICE: 'VOTE_TWICE',

	// things
	ROLES: {
		USER: 1,
		MODERATOR: 5,
		ADMIN: 10
	}
};
